### ISSUE TITLE
Error occurred while enabling FoxyMachines vDEV

### ISSUE THREAD

**Issue by 4o4E** [GallowsDove/FoxyMachines#20]
![image](https://user-images.githubusercontent.com/58851040/111792138-eaf61a80-88fe-11eb-9c12-380bc31f4654.png)
![image](https://user-images.githubusercontent.com/58851040/111792179-f8130980-88fe-11eb-846b-1af64fbb49c9.png)
![image](https://user-images.githubusercontent.com/58851040/111792447-3c060e80-88ff-11eb-82aa-c6e4ac3f89bb.png)
![image](https://user-images.githubusercontent.com/58851040/111789968-acf7f700-88fc-11eb-9359-75dbc9610b4b.png)

Complete error report:

[22:02:26] [Server thread/INFO]: [FoxyMachines] Enabling FoxyMachines vDEV - 37 (git 161adbcc)
[22:02:26] [Server thread/ERROR]: [FoxyMachines] Plugin FoxyMachines vDEV - 37 (git 161adbcc) has failed to register events for class me.gallowsdove.foxymachines.listeners.ForcefieldListener because io/github/thebusybiscuit/slimefun4/api/events/ExplosiveToolBreakBlocksEvent does not exist.
[22:02:26] [Server thread/ERROR]: Error occurred while enabling FoxyMachines vDEV - 37 (git 161adbcc) (Is it up to date?)
java.lang.IncompatibleClassChangeError: class me.gallowsdove.foxymachines.implementation.multiblock.SacrificialAltarPiece$1 has interface io.github.thebusybiscuit.slimefun4.core.handlers.BlockBreakHandler as super class
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1016) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:178) ~[patched_1.16.4.jar:git-Paper-416]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:216) ~[patched_1.16.4.jar:git-Paper-416]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:122) ~[patched_1.16.4.jar:git-Paper-416]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.4.jar:git-Paper-416]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at me.gallowsdove.foxymachines.implementation.multiblock.SacrificialAltarPiece.onBlockBreak(SacrificialAltarPiece.java:31) ~[?:?]
	at me.gallowsdove.foxymachines.implementation.multiblock.SacrificialAltarPiece.preRegister(SacrificialAltarPiece.java:27) ~[?:?]
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.SlimefunItem.register(SlimefunItem.java:426) ~[?:?]
	at me.gallowsdove.foxymachines.ItemSetup.init(Setup.java:226) ~[?:?]
	at me.gallowsdove.foxymachines.FoxyMachines.onEnable(FoxyMachines.java:49) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.4.jar:git-Paper-416]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.4.jar:git-Paper-416]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-416]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-416]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-416]
	at java.lang.Thread.run(Thread.java:832) [?:?]
[22:02:26] [Server thread/INFO]: [FoxyMachines] Disabling FoxyMachines vDEV - 37 (git 161adbcc)
[22:02:26] [Server thread/ERROR]: Error occurred while disabling FoxyMachines vDEV - 37 (git 161adbcc) (Is it up to date?)
java.lang.NullPointerException: null
	at java.io.File.<init>(File.java:279) ~[?:?]
	at me.gallowsdove.foxymachines.implementation.tools.BerryBushTrimmer.saveTrimmedBlocks(BerryBushTrimmer.java:82) ~[?:?]
	at me.gallowsdove.foxymachines.FoxyMachines.onDisable(FoxyMachines.java:63) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.4.jar:git-Paper-416]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.4.jar:git-Paper-416]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.4.jar:git-Paper-416]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.4.jar:git-Paper-416]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.4.jar:git-Paper-416]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.4.jar:git-Paper-416]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935) ~[patched_1.16.4.jar:git-Paper-416]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-416]
	at java.lang.Thread.run(Thread.java:832) [?:?]

**Comment by GallowsDove** [comment]
what sf version is 4.9-stable-210220? Make sure you use at least RC-21. Also update FoxyMachines to 39 please

**Comment by 4o4E** [comment]
https://github.com/StarWishsama/Slimefun4

**Comment by GallowsDove** [comment]
That isn't supported. However, if you use their pre-release v4.9-dev-210317 then I believe that it should work, otherwise you will have to wait for them to update to latest Slimefun version

**Comment by 4o4E** [comment]
OK, thanks for the answer
