### ISSUE TITLE
FoxyMachines error

### ISSUE THREAD

**Issue by jeffl1ma** [GallowsDove/FoxyMachines#65]
[04:59:56] [Server thread/WARN]: [FoxyMachines] Task #582 for FoxyMachines vDEV - 61 (git 265728f9) generated an exception
java.lang.IllegalArgumentException: Progress must be between 0.0 and 1.0 (1.8)
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220) ~[guava-31.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.boss.CraftBossBar.setProgress(CraftBossBar.java:158) ~[paper-1.19.3.jar:git-Paper-431]
	at me.gallowsdove.foxymachines.abstracts.CustomBoss.getBossBarForEntity(CustomBoss.java:132) ~[FoxyMachines - DEV 61 (git 26572).jar:?]
	at me.gallowsdove.foxymachines.abstracts.CustomBoss.onBossPattern(CustomBoss.java:104) ~[FoxyMachines - DEV 61 (git 26572).jar:?]
	at me.gallowsdove.foxymachines.implementation.mobs.PixieQueen.onBossPattern(PixieQueen.java:75) ~[FoxyMachines - DEV 61 (git 26572).jar:?]
	at me.gallowsdove.foxymachines.tasks.MobTicker.run(MobTicker.java:24) ~[FoxyMachines - DEV 61 (git 26572).jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-431]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[paper-1.19.3.jar:git-Paper-431]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1473) ~[paper-1.19.3.jar:git-Paper-431]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.19.3.jar:git-Paper-431]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-431]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-431]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-431]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

[05:06:25 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-431 (MC: 1.19.3)
Slimefun DEV - 1047 (git 84008330)
Metrics-Module #28
Java 17

Installed Addons: (22)
  Networks vDEV - 45 (git ade6fbd0)
  DyedBackpacks vDEV - 17 (git 8b329e96)
  ExtraTools vDEV - 36 (git 922c0324)
  AureliumSkills vBeta 1.3.14
  AngelChest v9.8.0
  Bump vBuild 31 zh-CN(SlimefunGuguProject) (git 4a1d7f6)
  HotbarPets vDEV - 38 (git fa6c871d)
  EcoPower vDEV - 5 (git 5c1ecd68)
  DynaTech vDEV - 194 (git 990c942e)
  ExtraGear vDEV - 13 (git c62047e2)
  SlimefunLuckyBlocks vDEV - 36 (git 60f0c8dc)
  SlimeHUD vDEV - 10 (git 7d1c666b)
  CMILib v1.2.4.5
  Supreme vDEV - 20 (git 4d8b06be)
  SimpleUtils vDEV - 15 (git 4250fd5e)
  RedProtect v7.7.3
  VillagerUtil vDEV - 1 (git 0a949b19)
  SoulJars vDEV - 23 (git b8358a1f)
  SlimyTreeTaps vDEV - 20 (git 963f0383)
  MobCapturer vDEV - 26 (git e0f006c2)
  PrivateStorage vDEV - 18 (git 5832db21)
  FluffyMachines vDEV - 130 (git 01c839cc)

**Comment by MeowIce** [comment]
I also had the same issue and it's spamming all over the console.
