### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by ZiwoxYT** [GallowsDove/FoxyMachines#80]
[20:57:54 ERROR]: Could not pass event EntityDamageByEntityEvent to FoxyMachines vDEV - 67 (git 0028aa93)
java.lang.IllegalArgumentException: Health value (22.593894958496094) must be between 0 and 20.0. (attribute base value: 20.0, player: .JufriHD)
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:472) ~[guava-31.1-jre.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:107) ~[gale-1.20.1.jar:git-Gale-"91ba163"]
        at me.gallowsdove.foxymachines.utils.Utils.dealDamageBypassingArmor(Utils.java:25) ~[FoxyMachines - DEV 67 (git 0028a).jar:?]
        at me.gallowsdove.foxymachines.listeners.BowListener.onHit(BowListener.java:40) ~[FoxyMachines - DEV 67 (git 0028a).jar:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:40) ~[gale-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[gale-api-1.20.1-R0.1-SNAPSHOT.jar:git-Gale-"91ba163"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[gale-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[gale-1.20.1.jar:git-Gale-"91ba163"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[gale-1.20.1.jar:git-Gale-"91ba163"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[gale-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEvent(CraftEventFactory.java:264) ~[gale-1.20.1.jar:git-Gale-"91ba163"]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1215) ~[gale-1.20.1.jar:git-Gale-"91ba163"]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1070) ~[gale-1.20.1.jar:git-Gale-"91ba163"]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1014) ~[gale-1.20.1.jar:git-Gale-"91ba163"]
        at org.bukkit.craftbukkit.v1_20_R1.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1249) ~[gale-1.20.1.jar:git-Gale-"91ba163"]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2228) ~[?:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1070) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1437) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:977) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1129) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.onHitEntity(AbstractArrow.java:402) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.onHit(Projectile.java:235) ~[?:?]
        at net.minecraft.world.entity.projectile.Projectile.preOnHit(Projectile.java:226) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.preOnHit(AbstractArrow.java:296) ~[?:?]
        at net.minecraft.world.entity.projectile.AbstractArrow.tick(AbstractArrow.java:232) ~[?:?]
        at net.minecraft.world.entity.projectile.Arrow.tick(Arrow.java:112) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1334) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$13(ServerLevel.java:857) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[gale-1.20.1.jar:git-Gale-"91ba163"]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:838) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1531) ~[gale-1.20.1.jar:git-Gale-"91ba163"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:457) ~[gale-1.20.1.jar:git-Gale-"91ba163"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1381) ~[gale-1.20.1.jar:git-Gale-"91ba163"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1159) ~[gale-1.20.1.jar:git-Gale-"91ba163"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[gale-1.20.1.jar:git-Gale-"91ba163"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by GallowsDove** [comment]
Could you provide some context when the error occurred please?

**Comment by GallowsDove** [comment]
Closing this due to lack of follow-up, I'll reopen if new information is provided
